---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(docs/generated/|\.min\.(js|css)$)
      - id: end-of-file-fixer
        exclude: ^(docs/generated/|\.min\.(js|css)$)
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-toml
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(docs/|tests/fixtures/|\.git/|\.github/|\.venv/)
      - id: ruff-format
        exclude: ^(docs/|tests/fixtures/|\.git/|\.github/|\.venv/)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        exclude: ^(tests/|docs/|scripts/|\.github/)
        args: [--no-strict-optional, --ignore-missing-imports]

  # JavaScript/TypeScript support
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        language_version: "20.8.0"
        additional_dependencies:
          - eslint@8.57.0
          - eslint-config-prettier@9.1.0
          - typescript@5.8.3
          - "@typescript-eslint/eslint-plugin@^8.31.0"
          - "@typescript-eslint/parser@^8.31.0"
          - "eslint-plugin-react@^7.33.0"
          - "eslint-plugin-react-native@^4.1.0"
        args: [--fix]
        language: node

  # Security checks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        name: "🔒 Detect hardcoded secrets"

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        exclude: ^(tests/|docs/)
        args: ["-c", "apps/backend/pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
