"""Add admin table

Revision ID: 222de4debd43
Revises: c9f8d1e2a5b4
Create Date: 2025-06-08 11:43:49.036846

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "222de4debd43"
down_revision: Union[str, None] = "c9f8d1e2a5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_admins_id"), "admins", ["id"], unique=False)
    op.create_index(op.f("ix_admins_user_id"), "admins", ["user_id"], unique=False)
    op.drop_index("ix_attorney_court_admissions_attorney_id", table_name="attorney_court_admissions")
    op.drop_index("ix_attorney_court_admissions_court_id", table_name="attorney_court_admissions")
    op.drop_index("ix_attorneys_email", table_name="attorneys")
    op.drop_index("ix_attorneys_state", table_name="attorneys")
    op.drop_index("ix_attorneys_zip_code", table_name="attorneys")
    op.drop_index("ix_attorneys_user_id", table_name="attorneys")
    op.create_index(op.f("ix_attorneys_user_id"), "attorneys", ["user_id"], unique=False)
    op.create_index(op.f("ix_attorneys_id"), "attorneys", ["id"], unique=False)
    op.drop_index("ix_clients_alien_registration_number", table_name="clients")
    op.drop_index("ix_clients_country_of_birth", table_name="clients")
    op.drop_index("ix_clients_first_name", table_name="clients")
    op.drop_index("ix_clients_last_name", table_name="clients")
    op.drop_index("ix_clients_passport_number", table_name="clients")
    op.drop_index("ix_clients_student_id_number", table_name="clients")
    op.drop_index("ix_clients_user_id", table_name="clients")
    op.create_index(op.f("ix_clients_user_id"), "clients", ["user_id"], unique=False)
    op.create_index(op.f("ix_clients_id"), "clients", ["id"], unique=False)
    op.create_unique_constraint("uq_clients_student_id_number", "clients", ["student_id_number"])
    op.create_unique_constraint("uq_clients_alien_registration_number", "clients", ["alien_registration_number"])
    op.create_unique_constraint("uq_clients_passport_number", "clients", ["passport_number"])
    op.drop_constraint("courts_abbreviation_key", "courts", type_="unique")
    op.drop_index("ix_emergency_contacts_client_id", table_name="emergency_contacts")
    op.drop_index("ix_emergency_contacts_email", table_name="emergency_contacts")
    op.drop_index("ix_emergency_contacts_phone_number", table_name="emergency_contacts")
    op.create_index(op.f("ix_emergency_contacts_id"), "emergency_contacts", ["id"], unique=False)
    op.alter_column(
        "users",
        "cognito_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="User ID from AWS Cognito",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "user_type",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="Type of user: client, attorney, friend, admin",
        existing_nullable=False,
    )
    op.drop_constraint("users_cognito_id_key", "users", type_="unique")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_unique_constraint("users_cognito_id_key", "users", ["cognito_id"])
    op.alter_column(
        "users",
        "user_type",
        existing_type=sa.VARCHAR(length=20),
        comment="Type of user: client, attorney, friend, admin",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "cognito_id",
        existing_type=sa.VARCHAR(length=36),
        comment="User ID from AWS Cognito",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_emergency_contacts_id"), table_name="emergency_contacts")
    op.create_index("ix_emergency_contacts_phone_number", "emergency_contacts", ["phone_number"], unique=False)
    op.create_index("ix_emergency_contacts_email", "emergency_contacts", ["email"], unique=False)
    op.create_index("ix_emergency_contacts_client_id", "emergency_contacts", ["client_id"], unique=False)
    op.create_unique_constraint("courts_abbreviation_key", "courts", ["abbreviation"])
    op.drop_constraint(None, "clients", type_="unique")
    op.drop_constraint(None, "clients", type_="unique")
    op.drop_constraint(None, "clients", type_="unique")
    op.drop_index(op.f("ix_clients_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_user_id"), table_name="clients")
    op.create_index("ix_clients_user_id", "clients", ["user_id"], unique=True)
    op.create_index("ix_clients_student_id_number", "clients", ["student_id_number"], unique=True)
    op.create_index("ix_clients_passport_number", "clients", ["passport_number"], unique=True)
    op.create_index("ix_clients_last_name", "clients", ["last_name"], unique=False)
    op.create_index("ix_clients_first_name", "clients", ["first_name"], unique=False)
    op.create_index("ix_clients_country_of_birth", "clients", ["country_of_birth"], unique=False)
    op.create_index("ix_clients_alien_registration_number", "clients", ["alien_registration_number"], unique=True)
    op.drop_index(op.f("ix_attorneys_id"), table_name="attorneys")
    op.drop_index(op.f("ix_attorneys_user_id"), table_name="attorneys")
    op.create_index("ix_attorneys_user_id", "attorneys", ["user_id"], unique=True)
    op.create_index("ix_attorneys_zip_code", "attorneys", ["zip_code"], unique=False)
    op.create_index("ix_attorneys_state", "attorneys", ["state"], unique=False)
    op.create_index("ix_attorneys_email", "attorneys", ["email"], unique=True)
    op.create_index("ix_attorney_court_admissions_court_id", "attorney_court_admissions", ["court_id"], unique=False)
    op.create_index(
        "ix_attorney_court_admissions_attorney_id", "attorney_court_admissions", ["attorney_id"], unique=False
    )
    op.drop_index(op.f("ix_admins_user_id"), table_name="admins")
    op.drop_index(op.f("ix_admins_id"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
