"""Replace Client with ClientProfile and add hybrid architecture support

Revision ID: 01a2b3c4d5e6
Revises: 222de4debd43
Create Date: 2025-01-22 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01a2b3c4d5e6"
down_revision: Union[str, None] = "222de4debd43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add primary_role column to users table for hybrid architecture
    op.add_column(
        "users",
        sa.Column(
            "primary_role",
            sa.String(length=20),
            nullable=True,
            comment="Primary role: attorney, client_helper, or admin",
        ),
    )
    op.create_index(op.f("ix_users_primary_role"), "users", ["primary_role"], unique=False)

    # Create client_profiles table
    op.create_table(
        "client_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "profile_name",
            sa.String(length=255),
            nullable=False,
            comment="Display name for profile (e.g., 'John Doe', 'My Son')",
        ),
        sa.Column(
            "is_self",
            sa.Boolean(),
            default=False,
            nullable=False,
            comment="True if this profile represents the account holder",
        ),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("country_of_birth", sa.String(length=100), nullable=False),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("alien_registration_number", sa.String(length=20), nullable=True),
        sa.Column("passport_number", sa.String(length=20), nullable=True),
        sa.Column("school_name", sa.String(length=255), nullable=True),
        sa.Column("student_id_number", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alien_registration_number"),
        sa.UniqueConstraint("passport_number"),
        sa.UniqueConstraint("student_id_number"),
    )
    op.create_index(op.f("ix_client_profiles_id"), "client_profiles", ["id"], unique=False)
    op.create_index(op.f("ix_client_profiles_user_id"), "client_profiles", ["user_id"], unique=False)

    # Update emergency_contacts to reference client_profiles instead of clients
    op.drop_constraint("emergency_contacts_client_id_fkey", "emergency_contacts", type_="foreignkey")
    op.drop_column("emergency_contacts", "client_id")
    op.add_column("emergency_contacts", sa.Column("client_profile_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_emergency_contacts_client_profile_id",
        "emergency_contacts",
        "client_profiles",
        ["client_profile_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Remove legacy clients table since we have no production data
    op.drop_table("clients")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Recreate clients table (restore previous schema)
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("country_of_birth", sa.String(length=100), nullable=False),
        sa.Column("nationality", sa.String(length=100), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("alien_registration_number", sa.String(length=20), nullable=True),
        sa.Column("passport_number", sa.String(length=20), nullable=True),
        sa.Column("school_name", sa.String(length=255), nullable=True),
        sa.Column("student_id_number", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alien_registration_number"),
        sa.UniqueConstraint("passport_number"),
        sa.UniqueConstraint("student_id_number"),
    )

    # Revert emergency_contacts to reference clients instead of client_profiles
    op.drop_constraint("fk_emergency_contacts_client_profile_id", "emergency_contacts", type_="foreignkey")
    op.drop_column("emergency_contacts", "client_profile_id")
    op.add_column("emergency_contacts", sa.Column("client_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "emergency_contacts_client_id_fkey",
        "emergency_contacts",
        "clients",
        ["client_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Drop client_profiles table
    op.drop_index(op.f("ix_client_profiles_user_id"), table_name="client_profiles")
    op.drop_index(op.f("ix_client_profiles_id"), table_name="client_profiles")
    op.drop_table("client_profiles")

    # Drop primary_role column from users
    op.drop_index(op.f("ix_users_primary_role"), table_name="users")
    op.drop_column("users", "primary_role")

    # ### end Alembic commands ###
