"""Create district_court_contacts table and add relationship to courts

Revision ID: c2a8e3f9b1d0
Revises: bbde81766990
Create Date: 2025-05-07 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = "c2a8e3f9b1d0"
down_revision: Union[str, None] = "bbde81766990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "district_court_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("court_id", sa.Integer(), nullable=False),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("hours", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=func.now(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["court_id"],
            ["courts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_district_court_contacts_court_id"), "district_court_contacts", ["court_id"], unique=False)
    op.create_index(op.f("ix_district_court_contacts_id"), "district_court_contacts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_district_court_contacts_id"), table_name="district_court_contacts")
    op.drop_index(op.f("ix_district_court_contacts_court_id"), table_name="district_court_contacts")
    op.drop_table("district_court_contacts")
    # ### end Alembic commands ###
