services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/habeas
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations

    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habeas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  mobile:
#    build:
#      context: ./mobile
#      dockerfile: Dockerfile
#    ports:
#      - "19000:19000"
#      - "19001:19001"
#      - "19002:19002"
#    volumes:
#      - ./mobile:/app
#      - /app/node_modules
#    environment:
#      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0

volumes:
  postgres_data:
