services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations

    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uv run alembic upgrade head
    env_file:
      - ../.env
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrations:/app/migrations
    depends_on:
      - db

volumes:
  postgres_data:
